name:          "Math in Decision Making"
description:   "Course Page for UNI Math 1100"
email:         theron.hitchman@uni.edu


url:           "http://theronhitchman.github.io"
baseurl:       "/decision-making"


markdown:      kramdown
highlighter:   pygments


section02url: "http://theronhitchman.github.io/decision-making/section02"
section04url: "http://theronhitchman.github.io/decision-making/section04"

# link urls

unimathurl: "http://www.uni.edu/math"
unichasurl: "http://www.uni.edu/chas/"
uniurl: "http://www.uni.edu"
